[build]
  # Directorio donde están las funciones serverless
  functions = "netlify/functions"
  # Comando de build a ejecutar
  command = "cd frontend && npm install --force --no-audit --no-fund && npm run build"
  # Directorio de salida
  publish = "frontend/dist"

# Regla de Redirect para que React Router maneje el enrutamiento
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Plugin para instalar automáticamente las dependencias de las functions
[[plugins]]
package = "@netlify/plugin-functions-install-core"
