[build]
  # Directorio base donde está el package.json del frontend
  base = "frontend"
  # Directorio donde están las funciones serverless
  functions = "netlify/functions"
  # Comando de build a ejecutar dentro del 'base'
  command = "pnpm run build"
  # Directorio de salida (relativo al 'base')
  publish = "frontend/dist"

# Regla de Redirect para que React Router maneje el enrutamiento
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200